pipeline {
    agent any
    environment {
        dockerHome = tool "myDocker"
		nodeHome = tool "myNodeJS"
		PATH = "$dockerHome/bin:$nodeHome/bin:$PATH"
    }
    stages {
        stage("Checkout") {
            steps {
                echo "Docker Home"
                sh "docker --version"
                echo "We have node"
                sh "node --version"
                echo "We have npm"
                sh "npm --version"
                echo "Path: $Path"
				echo "Build Number: $env.BUILD_NUMBER"
				echo "Build ID: $env.BUILD_ID"
				echo "Build URL: $env.BUILD_URL"
				echo "Build Tag: $env.BUILD_TAG"
				echo "Job Name: $env.JOB_NAME"
                echo "FINSIHED THESE STEPS"
            }
            post {
				always {
					echo "I run at the end of the build stage"
				}
			}
        }
        stage("Build Docker Image") {
            steps {
                withCredentials([file(credentialsId: "blog_mvc_env", variable: "ENV_FILE")]) {
                    echo "check before the mvc"
                    sh "pwd"
                    echo "check mvc now"
                    dir("blog_mvc") {
                        echo "current directory has to be blog"
                        sh "pwd"
                        script {
                            sh """
                            export \$(cat \$ENV_FILE | xargs)
                            # Build Docker image with environment variables
                            docker build \
                                --build-arg PORT=\$PORT \
                                --build-arg NODE_ENV=\$NODE_ENV \
                                --build-arg DB_USER=\$DB_USER \
                                --build-arg DB_HOST=\$DB_HOST \
                                --build-arg DB_NAME=\$DB_NAME \
                                --build-arg DB_PASSWORD=\$DB_PASSWORD \
                                --build-arg DB_PORT=\$DB_PORT \
                                --build-arg JWT_SECRET=\$JWT_SECRET \
                                -t customhaven/blog_mvc:${env.BUILD_TAG} .
                            """
                            dockerImage = docker.image("customhaven/blog_mvc:${env.BUILD_TAG}")
                        }
                    }
                }
            }
        }
        stage("Push Docker Image") {
			steps {
				script {
					docker.withRegistry("", "dockerhub") {
						dockerImage.push()
						dockerImage.push("${env.BUILD_TAG}")
					}
				}
			}
		}
    }
    post {
		always {
			echo "I always run"
		}
		success {
			echo "I run when successful"
		}
		failure {
			echo "I run when failed"
		}
	}
}